Repository project-momo/momo-be, pull requests merged in 2022-12, with the labels that each got.

#4 프로젝트 초기 세팅들 모음
  .github/ISSUE_TEMPLATE/new-feature.md
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/Dockerfile
  src/docker-compose.yml
  src/main/java/com/example/momobe/MomoBeApplication.java
  src/test/java/com/example/momobe/MomoBeApplicationTests.java
Labels: Feat

#5 Spring Security / WebConfig / TestContainer 설정 및 테스트 진행
  src/main/java/com/example/momobe/common/config/WebConfig.java
  src/main/java/com/example/momobe/common/exception/dto/ErrorResponseEntity.java
  src/main/java/com/example/momobe/common/exception/enums/ErrorCode.java
  src/main/java/com/example/momobe/common/exception/ui/ExceptionController.java
  src/main/java/com/example/momobe/common/resolver/JwtArgumentResolver.java
  src/main/java/com/example/momobe/common/resolver/Token.java
  src/main/java/com/example/momobe/common/resolver/UserInfo.java
  src/main/java/com/example/momobe/security/config/AuthenticationManagerConfig.java
  src/main/java/com/example/momobe/security/config/PasswordEncoderConfig.java
  src/main/java/com/example/momobe/security/config/SecurityConfig.java
  src/main/java/com/example/momobe/security/controller/TestController.java
  src/main/java/com/example/momobe/security/enums/SecurityConstants.java
  src/main/java/com/example/momobe/security/exception/InvalidJwtTokenException.java
  src/main/java/com/example/momobe/security/filter/CustomAuthenticationEntryPoint.java
  src/main/java/com/example/momobe/security/filter/ExceptionFilter.java
  src/main/java/com/example/momobe/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/example/momobe/security/provider/JwtAuthenticationProvider.java
  src/main/java/com/example/momobe/security/token/JwtAuthenticationToken.java
  src/main/java/com/example/momobe/security/util/JwtTokenUtil.java
  src/test/java/com/example/momobe/common/config/ApiDocumentUtils.java
  src/test/java/com/example/momobe/common/config/JpaQueryFactoryConfig.java
  src/test/java/com/example/momobe/common/config/RedisTestConfig.java
  src/test/java/com/example/momobe/common/config/SecurityTestConfig.java
  src/test/java/com/example/momobe/common/enums/TestConstants.java
  src/test/java/com/example/momobe/common/resolver/JwtArgumentResolverTest.java
  src/test/java/com/example/momobe/security/controller/TestControllerTest.java
  src/test/java/com/example/momobe/security/filter/ExceptionFilterTest.java
  src/test/java/com/example/momobe/security/filter/JwtAuthenticationFilterTest.java
  src/test/java/com/example/momobe/security/provider/JwtAuthenticationProviderTest.java
Labels: Feat

#7 유저 도메인 / 공통 클래스들 추가 및 테스트
  src/main/java/com/example/momobe/MomoBeApplication.java
  src/main/java/com/example/momobe/common/config/JpaQueryDslConfig.java
  src/main/java/com/example/momobe/common/config/RedisConfig.java
  src/main/java/com/example/momobe/common/exception/CustomException.java
  src/main/java/com/example/momobe/common/exception/enums/ErrorCode.java
  src/main/java/com/example/momobe/common/exception/ui/ExceptionController.java
  src/main/java/com/example/momobe/common/util/RandomKeyGenerator.java
  src/main/java/com/example/momobe/security/config/SecurityConfig.java
  src/main/java/com/example/momobe/security/enums/SecurityConstants.java
  src/main/java/com/example/momobe/security/oauth/CustomOAuth2Service.java
  src/main/java/com/example/momobe/security/oauth/OAuth2UserDto.java
  src/main/java/com/example/momobe/user/application/UserCommonService.java
  src/main/java/com/example/momobe/user/domain/Avatar.java
  src/main/java/com/example/momobe/user/domain/CustomUserRepository.java
  src/main/java/com/example/momobe/user/domain/Email.java
  src/main/java/com/example/momobe/user/domain/Nickname.java
  src/main/java/com/example/momobe/user/domain/Password.java
  src/main/java/com/example/momobe/user/domain/Point.java
  src/main/java/com/example/momobe/user/domain/Role.java
  src/main/java/com/example/momobe/user/domain/User.java
  src/main/java/com/example/momobe/user/domain/UserRepository.java
  src/main/java/com/example/momobe/user/domain/enums/RoleName.java
  src/main/java/com/example/momobe/user/dto/JwtTokenDto.java
  src/main/java/com/example/momobe/user/infrastructure/UserRepositoryImpl.java
  src/test/java/com/example/momobe/user/domain/PasswordTest.java
  src/test/java/com/example/momobe/user/domain/RoleTest.java
Labels: Feat

#9 모임 등록
  src/main/java/com/example/momobe/meeting/domain/Address.java
  src/main/java/com/example/momobe/meeting/domain/DateTime.java
  src/main/java/com/example/momobe/meeting/domain/Location.java
  src/main/java/com/example/momobe/meeting/domain/Meeting.java
  src/main/java/com/example/momobe/meeting/domain/MeetingRepository.java
  src/main/java/com/example/momobe/meeting/domain/MeetingStatus.java
  src/main/java/com/example/momobe/meeting/domain/PriceInfo.java
  src/main/java/com/example/momobe/meeting/domain/PricePolicy.java
  src/main/java/com/example/momobe/meeting/domain/ReservationStatus.java
  src/main/java/com/example/momobe/meeting/dto/MeetingRequestDto.java
  src/main/java/com/example/momobe/meeting/mapper/DateTimeMapper.java
  src/main/java/com/example/momobe/meeting/mapper/LocationMapper.java
  src/main/java/com/example/momobe/meeting/mapper/MeetingMapper.java
  src/main/java/com/example/momobe/meeting/mapper/PriceMapper.java
  src/main/java/com/example/momobe/meeting/presentation/MeetingRegistrationController.java
  src/test/java/com/example/momobe/common/enums/TestConstants.java
  src/test/java/com/example/momobe/meeting/presentation/MeetingRegistrationControllerTest.java
  src/test/java/com/example/momobe/security/provider/JwtAuthenticationProviderTest.java
Labels: Feat

#12 테스트케이스 추가, 예외 처리 리팩터링
  src/main/java/com/example/momobe/common/exception/CustomException.java
  src/main/java/com/example/momobe/common/exception/enums/ErrorCode.java
  src/main/java/com/example/momobe/common/resolver/JwtArgumentResolver.java
  src/main/java/com/example/momobe/common/util/RandomKeyGenerator.java
  src/main/java/com/example/momobe/security/enums/SecurityConstants.java
  src/main/java/com/example/momobe/security/infrastructure/JwtTokenUtilImpl.java
  src/main/java/com/example/momobe/security/oauth/CustomOAuth2Service.java
  src/main/java/com/example/momobe/user/application/UserCommonService.java
  src/main/java/com/example/momobe/user/domain/NotEnoughPointException.java
  src/main/java/com/example/momobe/user/domain/Password.java
  src/main/java/com/example/momobe/user/domain/Point.java
  src/main/java/com/example/momobe/user/domain/User.java
  src/main/java/com/example/momobe/user/domain/UserNotFoundException.java
  src/main/java/com/example/momobe/user/infrastructure/RandomPasswordGeneratorImpl.java
  src/main/java/com/example/momobe/user/infrastructure/UnableToProcessException.java
  src/main/java/com/example/momobe/user/infrastructure/UserRepositoryImpl.java
  src/test/java/com/example/momobe/common/config/SecurityTestConfig.java
  src/test/java/com/example/momobe/common/enums/TestConstants.java
  src/test/java/com/example/momobe/user/domain/PointTest.java
  src/test/java/com/example/momobe/user/domain/UserRepositoryTest.java
  src/test/java/com/example/momobe/user/domain/UserTest.java
  src/test/java/com/example/momobe/user/infrastructure/UserRepositoryImplTest.java
Labels: Feat, Refactor

#13 레디스 스토어 구현, OAuth2 로그인 로직 구현 + 테스트
  src/main/java/com/example/momobe/common/domain/BaseTime.java
  src/main/java/com/example/momobe/common/domain/RandomKeyGenerator.java
  src/main/java/com/example/momobe/common/domain/RedisStore.java
  src/main/java/com/example/momobe/common/infrastructure/RedisStoreImpl.java
  src/main/java/com/example/momobe/security/domain/JwtTokenUtil.java
  src/main/java/com/example/momobe/security/oauth/CustomOAuth2Service.java
  src/main/java/com/example/momobe/security/oauth/OAuth2SuccessHandler.java
  src/main/java/com/example/momobe/security/provider/JwtAuthenticationProvider.java
  src/main/java/com/example/momobe/user/application/GenerateTokenService.java
  src/main/java/com/example/momobe/user/domain/CustomUserRepository.java
  src/main/java/com/example/momobe/user/domain/Email.java
  src/main/java/com/example/momobe/user/domain/Nickname.java
  src/main/java/com/example/momobe/user/domain/RandomPasswordGenerator.java
  src/main/java/com/example/momobe/user/domain/User.java
  src/main/java/com/example/momobe/user/domain/UserRedisStore.java
  src/main/java/com/example/momobe/user/dto/RedisUserDto.java
  src/main/java/com/example/momobe/user/infrastructure/RandomPasswordGeneratorImpl.java
  src/main/java/com/example/momobe/user/mapper/UserMapper.java
  src/test/java/com/example/momobe/common/config/SecurityTestConfig.java
  src/test/java/com/example/momobe/common/resolver/JwtArgumentResolverTest.java
  src/test/java/com/example/momobe/common/util/RandomPasswordGeneratorTest.java
  src/test/java/com/example/momobe/security/controller/TestControllerTest.java
  src/test/java/com/example/momobe/security/provider/JwtAuthenticationProviderTest.java
  src/test/java/com/example/momobe/user/domain/PasswordTest.java
  src/test/java/com/example/momobe/user/domain/UserRepositoryTest.java
  src/test/java/com/example/momobe/user/domain/UserTest.java
  src/test/java/com/example/momobe/user/infrastructure/UserRepositoryImplTest.java
  src/test/java/com/example/momobe/user/mapper/UserMapperTest.java
Labels: Feat, Refactor

#14 GenerateTokenService 단위 테스트 추가 및 Redis 통합 테스트 추가
  src/main/java/com/example/momobe/common/domain/RedisStore.java
  src/main/java/com/example/momobe/user/application/GenerateTokenService.java
  src/test/java/com/example/momobe/common/domain/RedisStoreTest.java
  src/test/java/com/example/momobe/user/application/GenerateTokenServiceTest.java
Labels: Feat

#20 로그아웃 로직 구현 및 통합, 단위테스트 / 토큰 재발행 로직 구현 및 통합, 단위 테스트
  src/main/java/com/example/momobe/security/oauth/CustomOAuth2Service.java
  src/main/java/com/example/momobe/user/application/GenerateTokenService.java
  src/main/java/com/example/momobe/user/application/LogoutService.java
  src/main/java/com/example/momobe/user/application/ReissueTokenService.java
  src/main/java/com/example/momobe/user/domain/Role.java
  src/main/java/com/example/momobe/user/domain/TokenNotFoundException.java
  src/main/java/com/example/momobe/user/domain/User.java
  src/main/java/com/example/momobe/user/ui/TokenController.java
  src/test/java/com/example/momobe/user/application/LogoutServiceTest.java
  src/test/java/com/example/momobe/user/application/ReissueTokenServiceTest.java
  src/test/java/com/example/momobe/user/integration/Logout_IntegrationTest.java
  src/test/java/com/example/momobe/user/integration/Reissue_IntegrationTest.java
  src/test/java/com/example/momobe/user/ui/TokenControllerTest.java
Labels: Feat

#25 Meeting 리스트 조회
  src/docs/asciidoc/index.adoc
  src/main/java/com/example/momobe/common/dto/PageResponseDto.java
  src/main/java/com/example/momobe/meeting/dao/MeetingQueryRepository.java
  src/main/java/com/example/momobe/meeting/dto/HostResponseDto.java
  src/main/java/com/example/momobe/meeting/dto/MeetingResponseDto.java
  src/main/java/com/example/momobe/meeting/ui/MeetingQueryController.java
  src/main/java/com/example/momobe/meeting/ui/MeetingRegistrationController.java
  src/main/resources/static/docs/index.html
  src/test/java/com/example/momobe/common/enums/PageConstants.java
  src/test/java/com/example/momobe/common/util/ReflectionUtil.java
  src/test/java/com/example/momobe/meeting/ui/MeetingQueryControllerTest.java
  src/test/java/com/example/momobe/meeting/ui/MeetingRegistrationControllerTest.java
Labels: Feat

#27 질문 작성 로직 및 테스트
  src/main/java/com/example/momobe/answer/domain/Answer.java
  src/main/java/com/example/momobe/answer/domain/AnswerRepository.java
  src/main/java/com/example/momobe/answer/domain/Content.java
  src/main/java/com/example/momobe/answer/domain/Meeting.java
  src/main/java/com/example/momobe/answer/domain/Question.java
  src/main/java/com/example/momobe/answer/domain/Writer.java
  src/main/java/com/example/momobe/meeting/domain/Meeting.java
  src/main/java/com/example/momobe/meeting/ui/MeetingRegistrationController.java
  src/main/java/com/example/momobe/question/domain/Content.java
  src/main/java/com/example/momobe/question/domain/Meeting.java
  src/main/java/com/example/momobe/question/domain/Question.java
  src/main/java/com/example/momobe/question/domain/QuestionRepository.java
  src/main/java/com/example/momobe/question/domain/Writer.java
  src/main/java/com/example/momobe/question/domain/enums/QuestionStateType.java
  src/main/java/com/example/momobe/question/dto/in/QuestionDto.java
  src/main/java/com/example/momobe/question/dto/out/ResponseQuestionDto.java
  src/main/java/com/example/momobe/question/infrastructure/QuestionQueryRepository.java
  src/main/java/com/example/momobe/question/mapper/QuestionMapper.java
  src/main/java/com/example/momobe/question/ui/QuestionController.java
  src/main/java/com/example/momobe/user/application/UserCommonService.java
  src/main/java/com/example/momobe/user/controller/UserController.java
  src/main/java/com/example/momobe/user/domain/User.java
  src/main/java/com/example/momobe/user/dto/RedisUserDto.java
  src/test/java/com/example/momobe/question/infrastructure/QuestionQueryRepositoryTest.java
  src/test/java/com/example/momobe/question/integration/PostQuestion_IntegrationTest.java
  src/test/java/com/example/momobe/question/ui/QuestionControllerTest.java
Labels: Feat

#28 답변 작성 로직 구현 및 테스트코드
  src/main/java/com/example/momobe/answer/domain/Meeting.java
  src/main/java/com/example/momobe/answer/dto/AnswerDto.java
  src/main/java/com/example/momobe/answer/mapper/AnswerMapper.java
  src/main/java/com/example/momobe/answer/ui/AnswerController.java
  src/test/java/com/example/momobe/answer/integration/PostAnswer_IntegrationTest.java
  src/test/java/com/example/momobe/answer/mapper/AnswerMapperTest.java
  src/test/java/com/example/momobe/answer/ui/AnswerControllerTest.java
  src/test/java/com/example/momobe/question/mapper/QuestionMapperTest.java
Labels: Feat

#29 질문 / 답변 조회 구현 및 테스트
  src/main/java/com/example/momobe/question/domain/Writer.java
  src/main/java/com/example/momobe/question/infrastructure/QuestionQueryRepository.java
  src/main/java/com/example/momobe/question/ui/QuestionController.java
  src/test/java/com/example/momobe/question/integration/GetQuestions_IntegrationTest.java
  src/test/java/com/example/momobe/question/ui/QuestionControllerTest.java
Labels: Feat

#31 Meeting 도메인 모델 수정
  src/docs/asciidoc/index.adoc
  src/main/java/com/example/momobe/meeting/domain/DateTime.java
  src/main/java/com/example/momobe/meeting/domain/Meeting.java
  src/main/java/com/example/momobe/meeting/domain/enums/DatePolicy.java
  src/main/java/com/example/momobe/meeting/dto/MeetingRequestDto.java
  src/main/java/com/example/momobe/meeting/mapper/DateTimeMapper.java
  src/main/java/com/example/momobe/meeting/mapper/MeetingMapper.java
  src/main/resources/static/docs/index.html
  src/test/java/com/example/momobe/common/enums/TestConstants.java
  src/test/java/com/example/momobe/meeting/dto/DateTimeDtoTest.java
  src/test/java/com/example/momobe/meeting/dto/MeetingRequestDtoTest.java
  src/test/java/com/example/momobe/meeting/enums/MeetingConstant.java
  src/test/java/com/example/momobe/meeting/mapper/MeetingMapperTest.java
  src/test/java/com/example/momobe/meeting/ui/MeetingRegistrationControllerTest.java
  src/test/java/com/example/momobe/question/infrastructure/QuestionQueryRepositoryTest.java
  src/test/java/com/example/momobe/question/integration/GetQuestions_IntegrationTest.java
Labels: Feat

#33 Meeting > DateTimeInfo 생성
  src/main/java/com/example/momobe/meeting/domain/DateTimeInfo.java
  src/main/java/com/example/momobe/meeting/domain/Meeting.java
  src/main/java/com/example/momobe/meeting/domain/PriceInfo.java
  src/main/java/com/example/momobe/meeting/mapper/DateTimeMapper.java
  src/main/java/com/example/momobe/meeting/mapper/MeetingMapper.java
  src/test/java/com/example/momobe/meeting/enums/MeetingConstant.java
  src/test/java/com/example/momobe/meeting/integration/MeetingRegistration_IntegrationTest.java
  src/test/java/com/example/momobe/meeting/mapper/MeetingMapperTest.java
  src/test/java/com/example/momobe/question/infrastructure/QuestionQueryRepositoryTest.java
  src/test/java/com/example/momobe/question/integration/GetQuestions_IntegrationTest.java
Labels: Feat

#35 OAuth2 세팅 변경
  src/main/java/com/example/momobe/security/config/SecurityConfig.java
  src/main/java/com/example/momobe/security/enums/SecurityConstants.java
  src/main/java/com/example/momobe/security/oauth/OAuth2SuccessHandler.java
  src/main/java/com/example/momobe/user/domain/Point.java
  src/main/java/com/example/momobe/user/mapper/UserMapper.java
  src/main/java/com/example/momobe/user/ui/TokenController.java
  src/main/java/com/example/momobe/user/ui/UserController.java
  src/main/resources/static/docs/index.html
  src/test/java/com/example/momobe/question/ui/QuestionControllerTest.java
  src/test/java/com/example/momobe/user/domain/UserControllerTest.java
  src/test/java/com/example/momobe/user/domain/WithdrawalTest.java
  src/test/java/com/example/momobe/user/integration/Reissue_IntegrationTest.java
  src/test/java/com/example/momobe/user/ui/TokenControllerTest.java
Labels: Refactor

#38 게스트 로그인 구현 및 테스트
  src/main/java/com/example/momobe/user/application/GenerateGuestUserService.java
  src/main/java/com/example/momobe/user/ui/GuestController.java
  src/test/java/com/example/momobe/user/integration/Guest_IntegrationTest.java
  src/test/java/com/example/momobe/user/ui/GuestControllerTest.java
Labels: Feat

#41 feat : 예약 도메인
  src/main/java/com/example/momobe/reservation/domain/CheckReservationStatusService.java
  src/main/java/com/example/momobe/reservation/domain/CustomReservationRepository.java
  src/main/java/com/example/momobe/reservation/domain/Money.java
  src/main/java/com/example/momobe/reservation/domain/Reservation.java
  src/main/java/com/example/momobe/reservation/domain/ReservationDate.java
  src/main/java/com/example/momobe/reservation/domain/ReservationMemo.java
  src/main/java/com/example/momobe/reservation/domain/ReservationRepository.java
  src/main/java/com/example/momobe/reservation/domain/ReservedUser.java
  src/main/java/com/example/momobe/reservation/domain/enums/ReservationState.java
Labels: Feat

#42 Meeting 도메인 모델 수정
  src/main/java/com/example/momobe/address/domain/Address.java
  src/main/java/com/example/momobe/meeting/dao/MeetingQueryRepository.java
  src/main/java/com/example/momobe/meeting/domain/Address.java
  src/main/java/com/example/momobe/meeting/domain/DateTime.java
  src/main/java/com/example/momobe/meeting/domain/DateTimeInfo.java
  src/main/java/com/example/momobe/meeting/domain/Location.java
  src/main/java/com/example/momobe/meeting/domain/Meeting.java
  src/main/java/com/example/momobe/meeting/domain/PriceInfo.java
  src/main/java/com/example/momobe/meeting/domain/Time.java
  src/main/java/com/example/momobe/meeting/domain/enums/MeetingState.java
  src/main/java/com/example/momobe/meeting/domain/enums/ReservationState.java
  src/main/java/com/example/momobe/meeting/dto/MeetingRequestDto.java
  src/main/java/com/example/momobe/meeting/dto/MeetingResponseDto.java
  src/main/java/com/example/momobe/meeting/mapper/DateTimeMapper.java
  src/main/java/com/example/momobe/meeting/mapper/LocationMapper.java
  src/main/java/com/example/momobe/meeting/mapper/MeetingMapper.java
  src/main/java/com/example/momobe/meeting/mapper/PriceMapper.java
  src/test/java/com/example/momobe/meeting/dto/AddressDtoTest.java
  src/test/java/com/example/momobe/meeting/dto/LocationDtoTest.java
  src/test/java/com/example/momobe/meeting/dto/MeetingRequestDtoTest.java
  src/test/java/com/example/momobe/meeting/dto/PriceDtoTest.java
  src/test/java/com/example/momobe/meeting/enums/MeetingConstant.java
  src/test/java/com/example/momobe/meeting/integration/MeetingRegistration_IntegrationTest.java
  src/test/java/com/example/momobe/meeting/mapper/MeetingMapperTest.java
  src/test/java/com/example/momobe/meeting/ui/MeetingQueryControllerTest.java
  src/test/java/com/example/momobe/meeting/ui/MeetingRegistrationControllerTest.java
Labels: Feat

#50 예약 로직 및 테스트 (미완성) 중간 pr
  src/main/java/com/example/momobe/common/exception/enums/ErrorCode.java
  src/main/java/com/example/momobe/meeting/application/MeetingCommonService.java
  src/main/java/com/example/momobe/meeting/dao/MeetingDateQueryRepository.java
  src/main/java/com/example/momobe/meeting/dao/MeetingHostQueryRepository.java
  src/main/java/com/example/momobe/meeting/dao/MeetingQueryRepository.java
  src/main/java/com/example/momobe/meeting/domain/DateTimeInfo.java
  src/main/java/com/example/momobe/meeting/domain/Meeting.java
  src/main/java/com/example/momobe/meeting/domain/MeetingNotFoundException.java
  src/main/java/com/example/momobe/reservation/application/ReserveService.java
  src/main/java/com/example/momobe/reservation/domain/CheckExistReservationService.java
  src/main/java/com/example/momobe/reservation/domain/CheckReservationStatusService.java
  src/main/java/com/example/momobe/reservation/domain/CustomReservationRepository.java
  src/main/java/com/example/momobe/reservation/domain/Money.java
  src/main/java/com/example/momobe/reservation/domain/Reservation.java
  src/main/java/com/example/momobe/reservation/domain/ReservationDate.java
  src/main/java/com/example/momobe/reservation/domain/ReservationMemo.java
  src/main/java/com/example/momobe/reservation/domain/ReservationNotPossibleException.java
  src/main/java/com/example/momobe/reservation/domain/ReservationRepository.java
  src/main/java/com/example/momobe/reservation/domain/ReservedUser.java
  src/main/java/com/example/momobe/reservation/dto/CurrentReservationResponseDto.java
  src/main/java/com/example/momobe/reservation/dto/in/RequestReservationDto.java
  src/main/java/com/example/momobe/reservation/infrastructure/CustomJpaQueryRepositoryImpl.java
  src/main/java/com/example/momobe/reservation/mapper/ReservationMapper.java
  src/main/java/com/example/momobe/reservation/ui/ReservationController.java
  src/main/java/com/example/momobe/security/config/SecurityConfig.java
  src/main/java/com/example/momobe/user/domain/User.java
  src/main/resources/static/docs/index.html
  src/test/java/com/example/momobe/meeting/application/MeetingCommonServiceTest.java
  src/test/java/com/example/momobe/meeting/domain/MeetingTest.java
  src/test/java/com/example/momobe/reservation/domain/CheckExistReservationServiceTest.java
  src/test/java/com/example/momobe/reservation/domain/CustomReservationRepositoryTest.java
  src/test/java/com/example/momobe/reservation/mapper/ReservationMapperTest.java
  src/test/java/com/example/momobe/user/domain/UserControllerTest.java
Labels: Feat

#54 참여 모임 목록 조회 구현
  src/docs/asciidoc/index.adoc
  src/main/java/com/example/momobe/meeting/dao/MeetingParticipantQueryRepository.java
  src/main/java/com/example/momobe/meeting/dto/MeetingHostResponseDto.java
  src/main/java/com/example/momobe/meeting/dto/MeetingParticipantResponseDto.java
  src/main/java/com/example/momobe/reservation/domain/Reservation.java
  src/test/java/com/example/momobe/meeting/dao/MeetingParticipantQueryRepositoryTest.java
  src/test/java/com/example/momobe/meeting/integration/MeetingMyPageQuery_IntegrationTest.java
  src/test/java/com/example/momobe/meeting/ui/MeetingMyPageQueryControllerTest.java
Labels: Feat
