Repository project-momo/momo-be, pull requests merged in 2023-01, with the labels that each got.

#58 모임 상세 조회 구현
  src/docs/asciidoc/index.adoc
  src/main/java/com/example/momobe/meeting/dao/MeetingDetailQueryRepository.java
  src/main/java/com/example/momobe/meeting/dao/MeetingHostQueryRepository.java
  src/main/java/com/example/momobe/meeting/dao/MeetingParticipantQueryRepository.java
  src/main/java/com/example/momobe/meeting/dao/MeetingQueryRepository.java
  src/main/java/com/example/momobe/meeting/domain/Meeting.java
  src/main/java/com/example/momobe/meeting/dto/MeetingDateTimeDto.java
  src/main/java/com/example/momobe/meeting/dto/MeetingDetailResponseDto.java
  src/main/java/com/example/momobe/meeting/dto/MeetingHostResponseDto.java
  src/main/java/com/example/momobe/meeting/dto/MeetingParticipantResponseDto.java
  src/main/java/com/example/momobe/meeting/dto/MeetingResponseDto.java
  src/main/java/com/example/momobe/meeting/dto/MeetingUserResponseWithEmailDto.java
  src/main/java/com/example/momobe/meeting/ui/MeetingQueryController.java
  src/main/java/com/example/momobe/question/ui/QuestionController.java
  src/main/java/com/example/momobe/user/domain/Avatar.java
  src/test/java/com/example/momobe/meeting/dao/MeetingDetailQueryRepositoryTest.java
  src/test/java/com/example/momobe/meeting/enums/MeetingConstants.java
  src/test/java/com/example/momobe/meeting/integration/MeetingDetailQuery_IntegrationTest.java
  src/test/java/com/example/momobe/meeting/mapper/MeetingMapperTest.java
  src/test/java/com/example/momobe/meeting/ui/MeetingMyPageQueryControllerTest.java
  src/test/java/com/example/momobe/meeting/ui/MeetingQueryControllerTest.java
  src/test/java/com/example/momobe/question/integration/GetQuestions_IntegrationTest.java
  src/test/java/com/example/momobe/question/ui/QuestionControllerTest.java
Labels: Feat

#67 예약 기능 업데이트 및 테스트 , 예약 기능과 연관 있는 결제 관련 기능 추가
  src/main/java/com/example/momobe/common/exception/CustomException.java
  src/main/java/com/example/momobe/common/exception/dto/ErrorResponseEntity.java
  src/main/java/com/example/momobe/common/exception/enums/ErrorCode.java
  src/main/java/com/example/momobe/common/exception/ui/ExceptionController.java
  src/main/java/com/example/momobe/common/resolver/JwtArgumentResolver.java
  src/main/java/com/example/momobe/common/resolver/UserInfo.java
  src/main/java/com/example/momobe/meeting/dao/MeetingDateQueryRepository.java
  src/main/java/com/example/momobe/meeting/domain/DateTimeInfo.java
  src/main/java/com/example/momobe/meeting/domain/Meeting.java
  src/main/java/com/example/momobe/payment/application/SavePaymentService.java
  src/main/java/com/example/momobe/payment/domain/Payment.java
  src/main/java/com/example/momobe/payment/domain/PaymentRepository.java
  src/main/java/com/example/momobe/payment/domain/enums/PayState.java
  src/main/java/com/example/momobe/payment/domain/enums/PayType.java
  src/main/java/com/example/momobe/payment/mapper/PaymentMapper.java
  src/main/java/com/example/momobe/reservation/application/ReserveService.java
  src/main/java/com/example/momobe/reservation/domain/CountExistReservationService.java
  src/main/java/com/example/momobe/reservation/domain/Money.java
  src/main/java/com/example/momobe/reservation/domain/Reservation.java
  src/main/java/com/example/momobe/reservation/domain/ReservationNotPossibleException.java
  src/main/java/com/example/momobe/reservation/dto/in/RequestReservationDto.java
  src/main/java/com/example/momobe/reservation/dto/out/PaymentResponseDto.java
  src/main/java/com/example/momobe/reservation/dto/out/ReservationPaymentDto.java
  src/main/java/com/example/momobe/reservation/mapper/ReservationMapper.java
  src/main/java/com/example/momobe/reservation/ui/ReservationController.java
  src/test/java/com/example/momobe/meeting/domain/DateTimeInfoTest.java
  src/test/java/com/example/momobe/meeting/domain/MeetingTest.java
  src/test/java/com/example/momobe/reservation/application/ReserveServiceTest.java
  src/test/java/com/example/momobe/reservation/domain/CountExistReservationServiceTest.java
  src/test/java/com/example/momobe/reservation/mapper/ReservationMapperTest.java
  src/test/java/com/example/momobe/reservation/ui/ReservationControllerTest.java
Labels: Feat

#68 예약 기능 구현 1차 완료
  src/main/java/com/example/momobe/common/exception/enums/ErrorCode.java
  src/main/java/com/example/momobe/meeting/domain/DateTimeInfo.java
  src/main/java/com/example/momobe/meeting/domain/Meeting.java
  src/main/java/com/example/momobe/payment/domain/Payment.java
  src/main/java/com/example/momobe/reservation/application/ReserveService.java
  src/main/java/com/example/momobe/reservation/dto/in/RequestReservationDto.java
  src/main/java/com/example/momobe/reservation/dto/out/PaymentResponseDto.java
  src/main/java/com/example/momobe/reservation/ui/ReservationController.java
  src/test/java/com/example/momobe/meeting/domain/MeetingTest.java
  src/test/java/com/example/momobe/reservation/application/ReserveServiceTest.java
  src/test/java/com/example/momobe/reservation/dto/in/RequestReservationDtoTest.java
  src/test/java/com/example/momobe/reservation/integration/ReservationIntegrationTest.java
  src/test/java/com/example/momobe/reservation/ui/ReservationControllerTest.java
Labels: Feat

#81 모임 상세 조회 > 질문/답변 추가
  src/main/java/com/example/momobe/answer/domain/Content.java
  src/main/java/com/example/momobe/meeting/dao/MeetingDetailQueryRepository.java
  src/main/java/com/example/momobe/meeting/dao/MeetingParticipantQueryRepository.java
  src/main/java/com/example/momobe/meeting/domain/DateTimeInfo.java
  src/main/java/com/example/momobe/meeting/dto/MeetingDetailResponseDto.java
  src/main/java/com/example/momobe/meeting/mapper/DateTimeMapper.java
  src/main/java/com/example/momobe/question/domain/Content.java
  src/main/java/com/example/momobe/question/infrastructure/QuestionQueryRepository.java
  src/test/java/com/example/momobe/meeting/dao/MeetingDetailQueryRepositoryTest.java
  src/test/java/com/example/momobe/meeting/integration/MeetingDetailQuery_IntegrationTest.java
  src/test/java/com/example/momobe/meeting/mapper/MeetingMapperTest.java
  src/test/java/com/example/momobe/meeting/ui/MeetingQueryControllerTest.java
Labels: Feat

#82 주최 모임/참여 모임 목록 조회 리팩토링
  src/main/java/com/example/momobe/meeting/dao/MeetingDetailQueryRepository.java
  src/main/java/com/example/momobe/meeting/dao/MeetingHostQueryRepository.java
  src/main/java/com/example/momobe/meeting/dao/MeetingParticipantQueryRepository.java
  src/main/java/com/example/momobe/meeting/dto/MeetingHostResponseDto.java
  src/main/java/com/example/momobe/meeting/dto/MeetingInfoDto.java
  src/test/java/com/example/momobe/meeting/ui/MeetingMyPageQueryControllerTest.java
Labels: Refactor

#85 모임 닫기 구현
  src/docs/asciidoc/meeting.adoc
  src/docs/asciidoc/reservation.adoc
  src/docs/asciidoc/user.adoc
  src/main/java/com/example/momobe/common/exception/enums/ErrorCode.java
  src/main/java/com/example/momobe/meeting/application/MeetingCommonService.java
  src/main/java/com/example/momobe/meeting/domain/CanNotChangeMeetingStateException.java
  src/main/java/com/example/momobe/meeting/domain/Meeting.java
  src/main/java/com/example/momobe/meeting/ui/MeetingCommandController.java
  src/main/java/com/example/momobe/meeting/ui/MeetingRegistrationController.java
  src/test/java/com/example/momobe/meeting/application/MeetingCommonServiceTest.java
  src/test/java/com/example/momobe/meeting/dao/MeetingDetailQueryRepositoryTest.java
  src/test/java/com/example/momobe/meeting/enums/MeetingConstants.java
  src/test/java/com/example/momobe/meeting/integration/MeetingCommand_IntegrationTest.java
  src/test/java/com/example/momobe/meeting/integration/MeetingDetailQuery_IntegrationTest.java
  src/test/java/com/example/momobe/meeting/ui/MeetingCommandControllerTest.java
  src/test/java/com/example/momobe/meeting/ui/MeetingMyPageQueryControllerTest.java
  src/test/java/com/example/momobe/meeting/ui/MeetingQueryControllerTest.java
Labels: Feat

#97 주소 조회 구현
  src/docs/asciidoc/all.adoc
  src/main/java/com/example/momobe/address/dao/AddressQueryRepository.java
  src/main/java/com/example/momobe/address/dto/AddressResponseDto.java
  src/main/java/com/example/momobe/address/ui/AddressQueryController.java
  src/main/java/com/example/momobe/meeting/dao/MeetingQueryRepository.java
  src/main/java/com/example/momobe/meeting/domain/CanNotUpdateMeetingException.java
  src/main/java/com/example/momobe/meeting/domain/Meeting.java
  src/test/java/com/example/momobe/address/Integration/AddressQuery_IntegrationTest.java
  src/test/java/com/example/momobe/address/dao/AddressQueryRepositoryTest.java
  src/test/java/com/example/momobe/address/ui/AddressQueryControllerTest.java
  src/test/java/com/example/momobe/meeting/application/MeetingCommonServiceTest.java
  src/test/java/com/example/momobe/meeting/dto/AddressDtoTest.java
Labels: Feat

#98 API 문서 수정 및 html 정리
  src/docs/asciidoc/all.adoc
  src/main/resources/static/docs/all.html
  src/main/resources/static/docs/index.html
  src/main/resources/static/docs/meeting.html
  src/main/resources/static/docs/qna.html
  src/main/resources/static/docs/reservation.html
  src/main/resources/static/docs/token.html
  src/main/resources/static/docs/user.html
Labels: documentation

#102 Tag 테이블 생성, MeetingRegistrationService 작성
  src/main/java/com/example/momobe/address/application/AddressCommonService.java
  src/main/java/com/example/momobe/address/domain/AddressRepository.java
  src/main/java/com/example/momobe/meeting/application/MeetingRegistrationService.java
  src/main/java/com/example/momobe/meeting/domain/Meeting.java
  src/main/java/com/example/momobe/meeting/mapper/MeetingMapper.java
  src/main/java/com/example/momobe/meeting/ui/MeetingRegistrationController.java
  src/main/java/com/example/momobe/tag/application/TagCommonService.java
  src/main/java/com/example/momobe/tag/domain/Tag.java
  src/main/java/com/example/momobe/tag/domain/TagRepository.java
  src/test/java/com/example/momobe/address/application/AddressCommonServiceTest.java
  src/test/java/com/example/momobe/meeting/application/MeetingRegistrationServiceTest.java
  src/test/java/com/example/momobe/meeting/dao/MeetingDatesQueryMapperTest.java
  src/test/java/com/example/momobe/meeting/integration/MeetingDatesQuery_IntegrationTest.java
  src/test/java/com/example/momobe/meeting/integration/MeetingRegistration_IntegrationTest.java
  src/test/java/com/example/momobe/meeting/mapper/MeetingMapperTest.java
  src/test/java/com/example/momobe/meeting/ui/MeetingRegistrationControllerTest.java
  src/test/java/com/example/momobe/reservation/application/ReserveServiceTest.java
  src/test/java/com/example/momobe/reservation/integration/ReservationIntegrationTest.java
  src/test/java/com/example/momobe/tag/application/TagCommonServiceTest.java
  src/test/java/com/example/momobe/tag/domain/TagRepositoryTest.java
Labels: Refactor

#108 모임 상세 조회 태그 추가
  src/main/java/com/example/momobe/meeting/dao/MeetingDetailQueryRepository.java
  src/main/java/com/example/momobe/meeting/dto/MeetingDetailResponseDto.java
  src/test/java/com/example/momobe/meeting/dao/MeetingDetailQueryRepositoryTest.java
  src/test/java/com/example/momobe/meeting/enums/MeetingConstants.java
  src/test/java/com/example/momobe/meeting/integration/MeetingDetailQuery_IntegrationTest.java
  src/test/java/com/example/momobe/meeting/ui/MeetingQueryControllerTest.java
Labels: Feat

#110 코드 리팩토링, 위치 변경
  src/main/java/com/example/momobe/address/application/AddressCommonService.java
  src/main/java/com/example/momobe/meeting/application/MeetingRegistrationService.java
  src/main/java/com/example/momobe/meeting/dao/MeetingDetailQueryRepository.java
  src/main/java/com/example/momobe/meeting/dao/MeetingHostQueryRepository.java
  src/main/java/com/example/momobe/meeting/dao/MeetingParticipantQueryRepository.java
  src/main/java/com/example/momobe/meeting/dao/MeetingQueryRepository.java
  src/main/java/com/example/momobe/meeting/dao/MonthlyMeetingScheduleInquiry.java
  src/main/java/com/example/momobe/meeting/dto/in/MeetingRequestDto.java
  src/main/java/com/example/momobe/meeting/dto/out/MeetingDateTimeDto.java
  src/main/java/com/example/momobe/meeting/dto/out/MeetingDetailResponseDto.java
  src/main/java/com/example/momobe/meeting/dto/out/MeetingHostResponseDto.java
  src/main/java/com/example/momobe/meeting/dto/out/MeetingInfoDto.java
  src/main/java/com/example/momobe/meeting/dto/out/MeetingParticipantResponseDto.java
  src/main/java/com/example/momobe/meeting/dto/out/MeetingResponseDto.java
  src/main/java/com/example/momobe/meeting/dto/out/MeetingUserResponseDto.java
  src/main/java/com/example/momobe/meeting/dto/out/MeetingUserResponseWithEmailDto.java
  src/main/java/com/example/momobe/meeting/dto/out/ResponseMeetingDatesDto.java
  src/main/java/com/example/momobe/meeting/mapper/DateTimeMapper.java
  src/main/java/com/example/momobe/meeting/mapper/MeetingMapper.java
  src/main/java/com/example/momobe/meeting/ui/MeetingDatesQueryController.java
  src/main/java/com/example/momobe/meeting/ui/MeetingMyPageQueryController.java
  src/main/java/com/example/momobe/meeting/ui/MeetingQueryController.java
  src/main/java/com/example/momobe/meeting/ui/MeetingRegistrationController.java
  src/test/java/com/example/momobe/address/Integration/AddressQuery_IntegrationTest.java
  src/test/java/com/example/momobe/address/application/AddressCommonServiceTest.java
  src/test/java/com/example/momobe/address/dao/AddressQueryRepositoryTest.java
  src/test/java/com/example/momobe/address/ui/AddressQueryControllerTest.java
  src/test/java/com/example/momobe/meeting/application/MeetingCommonServiceTest.java
  src/test/java/com/example/momobe/meeting/dao/MeetingDetailQueryRepositoryTest.java
  src/test/java/com/example/momobe/meeting/dao/MeetingHostQueryRepositoryTest.java
  src/test/java/com/example/momobe/meeting/dao/MeetingParticipantQueryRepositoryTest.java
  src/test/java/com/example/momobe/meeting/dao/MeetingQueryRepositoryTest.java
  src/test/java/com/example/momobe/meeting/dao/MonthlyMeetingScheduleInquiryTest.java
  src/test/java/com/example/momobe/meeting/dto/AddressDtoTest.java
  src/test/java/com/example/momobe/meeting/dto/DateTimeDtoTest.java
  src/test/java/com/example/momobe/meeting/dto/MeetingRequestDtoTest.java
  src/test/java/com/example/momobe/meeting/enums/MeetingConstants.java
  src/test/java/com/example/momobe/meeting/integration/MeetingCommand_IntegrationTest.java
  src/test/java/com/example/momobe/meeting/integration/MeetingDatesQuery_IntegrationTest.java
  src/test/java/com/example/momobe/meeting/integration/MeetingDetailQuery_IntegrationTest.java
  src/test/java/com/example/momobe/meeting/integration/MeetingMyPageQuery_IntegrationTest.java
  src/test/java/com/example/momobe/meeting/integration/MeetingQuery_IntegrationTest.java
  src/test/java/com/example/momobe/meeting/integration/MeetingRegistration_IntegrationTest.java
  src/test/java/com/example/momobe/meeting/mapper/MeetingMapperTest.java
  src/test/java/com/example/momobe/meeting/ui/MeetingCommandControllerTest.java
  src/test/java/com/example/momobe/meeting/ui/MeetingDatesQueryControllerTest.java
  src/test/java/com/example/momobe/meeting/ui/MeetingMyPageQueryControllerTest.java
  src/test/java/com/example/momobe/meeting/ui/MeetingQueryControllerTest.java
  src/test/java/com/example/momobe/meeting/ui/MeetingRegistrationControllerTest.java
  src/test/java/com/example/momobe/tag/domain/TagRepositoryTest.java
Labels: Refactor

#111 Meeting 관련 Repository import 수정
  src/main/java/com/example/momobe/meeting/dao/MeetingDetailQueryRepository.java
  src/main/java/com/example/momobe/meeting/dao/MeetingHostQueryRepository.java
  src/main/java/com/example/momobe/meeting/dao/MeetingParticipantQueryRepository.java
  src/main/java/com/example/momobe/meeting/dao/MeetingQueryRepository.java
Labels: bug

#112 모임 조회 로직 공통화
  src/main/java/com/example/momobe/meeting/application/MeetingCloseService.java
  src/main/java/com/example/momobe/meeting/application/MeetingCommonService.java
  src/main/java/com/example/momobe/meeting/dao/MeetingHostQueryRepository.java
  src/main/java/com/example/momobe/meeting/dao/MeetingInfoUtil.java
  src/main/java/com/example/momobe/meeting/dao/MeetingParticipantQueryRepository.java
  src/main/java/com/example/momobe/meeting/dao/MeetingQueryRepository.java
  src/main/java/com/example/momobe/meeting/ui/MeetingCommandController.java
  src/test/java/com/example/momobe/meeting/application/MeetingCloseServiceTest.java
  src/test/java/com/example/momobe/meeting/application/MeetingCommonServiceTest.java
  src/test/java/com/example/momobe/meeting/dao/MeetingParticipantQueryRepositoryTest.java
  src/test/java/com/example/momobe/meeting/integration/MeetingRegistration_IntegrationTest.java
Labels: Refactor

#113 결제 관련 로직 구현 및 테스트
  src/main/java/com/example/momobe/common/exception/enums/ErrorCode.java
  src/main/java/com/example/momobe/payment/application/PaymentCommonService.java
  src/main/java/com/example/momobe/payment/application/PaymentProgressService.java
  src/main/java/com/example/momobe/payment/application/PaymentRequestService.java
  src/main/java/com/example/momobe/payment/application/PaymentRestTemplate.java
  src/main/java/com/example/momobe/payment/application/PaymentRestTemplateImpl.java
  src/main/java/com/example/momobe/payment/application/PaymentSaveService.java
  src/main/java/com/example/momobe/payment/application/PaymentVerificationService.java
  src/main/java/com/example/momobe/payment/domain/Payment.java
  src/main/java/com/example/momobe/payment/domain/PaymentRepository.java
  src/main/java/com/example/momobe/payment/domain/UnableProceedPaymentException.java
  src/main/java/com/example/momobe/payment/dto/PaymentResultDto.java
  src/main/java/com/example/momobe/payment/ui/PaymentSuccessController.java
  src/test/java/com/example/momobe/payment/application/PaymentCommonServiceTest.java
  src/test/java/com/example/momobe/payment/application/PaymentProgressServiceTest.java
  src/test/java/com/example/momobe/payment/application/PaymentRequestServiceTest.java
  src/test/java/com/example/momobe/payment/application/PaymentRestTemplateImplTest.java
  src/test/java/com/example/momobe/payment/application/PaymentVerificationServiceTest.java
  src/test/java/com/example/momobe/payment/domain/PaymentTest.java
  src/test/java/com/example/momobe/payment/ui/PaymentSuccessControllerTest.java
Labels: Feat

#119 모임 등록/수정 테스트 에러 수정
  src/main/java/com/example/momobe/meeting/dto/in/MeetingUpdateDto.java
  src/test/java/com/example/momobe/meeting/enums/MeetingConstants.java
  src/test/java/com/example/momobe/meeting/integration/MeetingCommand_IntegrationTest.java
  src/test/java/com/example/momobe/meeting/integration/MeetingRegistration_IntegrationTest.java
Labels: bug

#120 모임이 닫히면 새로운 신청 모두 취소
  src/main/java/com/example/momobe/meeting/application/MeetingCloseService.java
  src/main/java/com/example/momobe/reservation/domain/ReservationRepository.java
  src/test/java/com/example/momobe/meeting/application/MeetingCloseServiceTest.java
Labels: Feat

#121 참여 모임 목록 조회 > paymentKey 추가
  src/main/java/com/example/momobe/meeting/dao/MeetingParticipantQueryRepository.java
  src/main/java/com/example/momobe/meeting/dto/out/MeetingParticipantResponseDto.java
  src/test/java/com/example/momobe/meeting/ui/MeetingMyPageQueryControllerTest.java
Labels: Feat

#123 모임 등록 날짜 검증 추가
  src/main/java/com/example/momobe/meeting/dto/in/MeetingRequestDto.java
  src/test/java/com/example/momobe/meeting/dto/DateTimeDtoTest.java
Labels: Feat

#124 모임 목록 조회 null 처리, 중복 조회 제거
  src/main/java/com/example/momobe/meeting/dao/MeetingHostQueryRepository.java
  src/main/java/com/example/momobe/meeting/dao/MeetingInfoUtil.java
  src/main/java/com/example/momobe/meeting/dao/MeetingParticipantQueryRepository.java
  src/main/java/com/example/momobe/meeting/dao/MeetingQueryRepository.java
  src/main/java/com/example/momobe/meeting/dto/out/MeetingInfoDto.java
  src/test/java/com/example/momobe/meeting/enums/MeetingConstants.java
  src/test/java/com/example/momobe/meeting/integration/MeetingCommand_IntegrationTest.java
  src/test/java/com/example/momobe/meeting/integration/MeetingRegistration_IntegrationTest.java
Labels: bug

#128 만든 모임 목록 조회 잘못된 조인 수정
  src/main/java/com/example/momobe/meeting/dao/MeetingHostQueryRepository.java
  src/main/java/com/example/momobe/meeting/dao/MeetingQueryRepository.java
  src/main/java/com/example/momobe/meeting/domain/enums/PricePolicy.java
  src/test/java/com/example/momobe/meeting/integration/MeetingMyPageQuery_IntegrationTest.java
Labels: bug

#129 모임 목록 조회 > 응답 컨텐츠 길이 수정
  src/main/java/com/example/momobe/meeting/dao/MeetingQueryRepository.java
Labels: Refactor

#131 만든 모임 목록 조회 > 조건 추가
  src/main/java/com/example/momobe/meeting/dao/MeetingHostQueryRepository.java
  src/test/java/com/example/momobe/meeting/integration/MeetingMyPageQuery_IntegrationTest.java
Labels: Refactor

#133 모임 등록/수정 > 태그 한글로 변경
  src/main/java/com/example/momobe/meeting/application/MeetingCommonService.java
  src/main/java/com/example/momobe/meeting/dao/MeetingDetailQueryRepository.java
  src/main/java/com/example/momobe/meeting/domain/enums/Tag.java
  src/main/java/com/example/momobe/meeting/dto/in/MeetingRequestDto.java
  src/main/java/com/example/momobe/meeting/dto/in/MeetingUpdateDto.java
  src/main/java/com/example/momobe/tag/application/TagCommonService.java
  src/main/java/com/example/momobe/tag/domain/Tag.java
  src/main/java/com/example/momobe/tag/domain/TagRepository.java
  src/test/java/com/example/momobe/meeting/dao/MeetingDetailQueryRepositoryTest.java
  src/test/java/com/example/momobe/meeting/enums/MeetingConstants.java
  src/test/java/com/example/momobe/meeting/integration/MeetingCommand_IntegrationTest.java
  src/test/java/com/example/momobe/meeting/integration/MeetingDetailQuery_IntegrationTest.java
  src/test/java/com/example/momobe/meeting/integration/MeetingRegistration_IntegrationTest.java
  src/test/java/com/example/momobe/tag/application/TagCommonServiceTest.java
  src/test/java/com/example/momobe/tag/domain/TagRepositoryTest.java
Labels: Refactor

#135 만든 모임 목록 조회 > 예약 식별자 추가
  src/main/java/com/example/momobe/meeting/dao/MeetingHostQueryRepository.java
  src/main/java/com/example/momobe/meeting/dto/out/MeetingHostResponseDto.java
  src/main/java/com/example/momobe/meeting/dto/out/MeetingInfoDto.java
  src/test/java/com/example/momobe/meeting/ui/MeetingMyPageQueryControllerTest.java
Labels: Feat

#145 모임 목록 조회 > 태그 검색 추가
  src/main/java/com/example/momobe/meeting/dao/MeetingQueryRepository.java
  src/main/java/com/example/momobe/meeting/ui/MeetingQueryController.java
  src/test/java/com/example/momobe/meeting/dao/MeetingQueryRepositoryTest.java
  src/test/java/com/example/momobe/meeting/enums/MeetingConstants.java
  src/test/java/com/example/momobe/meeting/integration/MeetingDetailQuery_IntegrationTest.java
  src/test/java/com/example/momobe/meeting/ui/MeetingQueryControllerTest.java
Labels: Feat

#155 모임 등록/수정 카테고리 한글로 변경
  src/main/java/com/example/momobe/meeting/domain/CategoryNotFoundException.java
  src/main/java/com/example/momobe/meeting/domain/enums/Category.java
  src/main/java/com/example/momobe/meeting/dto/in/MeetingRequestDto.java
  src/main/java/com/example/momobe/meeting/dto/in/MeetingUpdateDto.java
  src/main/java/com/example/momobe/meeting/mapper/MeetingMapper.java
  src/test/java/com/example/momobe/meeting/application/MeetingUpdateServiceTest.java
  src/test/java/com/example/momobe/meeting/enums/MeetingConstants.java
  src/test/java/com/example/momobe/meeting/mapper/MeetingMapperTest.java
Labels: Feat

#168 모임 상세 조회 AddressIds 추가
  src/main/java/com/example/momobe/meeting/dao/MeetingDetailQueryRepository.java
  src/main/java/com/example/momobe/meeting/dto/out/MeetingDetailResponseDto.java
  src/test/java/com/example/momobe/meeting/ui/MeetingQueryControllerTest.java
Labels: Feat
